In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('/Users/dipeshkumar/Downloads/Hrt.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [5]:
x = df.drop(columns='target')
y = df['target']

In [6]:
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [7]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=8)

In [9]:
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3
111,57,1,2,150,126,1,1,173,0,0.2,2,1,3
37,54,1,2,150,232,0,0,165,0,1.6,2,0,3
137,62,1,1,128,208,1,0,140,0,0.0,2,0,2
231,57,1,0,165,289,1,0,124,0,1.0,1,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,67,0,2,115,564,0,0,160,0,1.6,1,0,3
48,53,0,2,128,216,0,0,115,0,0.0,2,0,0
191,58,1,0,128,216,0,0,131,1,2.2,1,3,3
136,60,0,2,120,178,1,1,96,0,0.0,2,0,2
133,41,1,1,110,235,0,1,153,0,0.0,2,0,2

In [10]:
#Importing Base models
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression #META MODEL
from sklearn.ensemble import GradientBoostingClassifier

In [12]:
estimators = [ 
    ('rf', RandomForestClassifier(n_estimators=10,random_state=12)),
    ('knn', KNeighborsClassifier(n_neighbors=10)),
    ('gb', GradientBoostingClassifier())
    
]

In [13]:
from sklearn.ensemble import StackingClassifier

In [14]:
clf = StackingClassifier(estimators=estimators,
                        final_estimator=LogisticRegression(),
                        cv=10)

In [15]:
clf.fit(x_train,y_train)

StackingClassifier(cv=10,
                   estimators=[('rf',
                                RandomForestClassifier(n_estimators=10,
                                                       random_state=12)),
                               ('knn', KNeighborsClassifier(n_neighbors=10)),
                               ('gb', GradientBoostingClassifier())],
                   final_estimator=LogisticRegression())

In [18]:
y_pred = clf.predict(x_test)

In [19]:
y_pred

array([1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1])

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8032786885245902